apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nx27
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-nx27@sha256:a67e89babdd80e2060a8d279cb7ca45e96902fdcb6eacbc3581eb49257d2de30
        name: my-nodejs
        resources: {}
status: {}
